delete-all-clusters_pre_delete_state: default
pks-nsx-t-precheck_post_deploy_state: default
smoke-tests_post_deploy_state: default
upgrade-all-service-instances_post_deploy_state: default
wavefront-alert-creation_post_deploy_state: default
wavefront-alert-deletion_pre_delete_state: default
pivotal-container-service_instance_type: automatic
pivotal-container-service_max_in_flight: default
pivotal-container-service_persistent_disk_size: automatic
