cloud_provider_vsphere_vcenter_master_creds_password: ((vsphere_vcenter_password))
wavefront_enabled_wavefront_token: ((wavefront_token))
uaa_ldap_credentials_password: ((uaa_ldap_password))
pivotal-container-service_pks_tls_certificate: ((pivotal-container-service/pks_tls.certificate))
pivotal-container-service_pks_tls_privatekey: ((pivotal-container-service/pks_tls.private_key))
