clair_updater_interval: 0
initial_delay_minutes: 60
no_proxy: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair-adapter,chartmuseum,notary-server
with_clair: true
with_notary: true
smoke-testing_post_deploy_state: default
uaa-deregistration_pre_delete_state: default
harbor-app_instance_type: automatic
harbor-app_max_in_flight: default
harbor-app_persistent_disk_size: automatic
smoke-testing_instance_type: automatic
smoke-testing_max_in_flight: default
